### ISSUE TITLE
feat: backup of identities

### ISSUE THREAD

**Issue by iskdrews** [CryptKeeperZK/crypt-keeper-extension#257]
Encrypted backup of identities

```[tasklist]
### Tasks
- [x] Support services for backups
- [x] Implement download backup
- [x] Implement upload backup
- [x] Add ui for download backup
- [x] Check password before downloading backup
- [x] Support history for backups
- [x] Notifications
```

**Comment by iskdrews** [comment]
ZK Backup cloud serves: 
https://www.puzzle.ch/de/blog/articles/2018/03/06/how-to-create-a-secure-multi-crypto-currency-wallet-and-back-it-up-safely

**Comment by iskdrews** [comment]
@0xmad Should we close this?

**Comment by 0xmad** [comment]
@iskdrews no, it's still in progress.
