### ISSUE TITLE
feat: CK injection APIs v0.1.0

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#311]
Source: https://github.com/CryptKeeperZK/ck-team-discussions/blob/main/DappsConnectCK.md

```[tasklist]
### Tasks
- [ ] #312
- [ ] #318
- [ ] #317
- [ ] #315
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/334
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/335
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/590
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/623
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/625
```
