### ISSUE TITLE
feat: switch to a Monorepo

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#395]
```[tasklist]
### Tasks
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/419
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/420
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/421
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/422
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/423
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/424
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/425
```
