### ISSUE TITLE
bug: provider APIs are not all wrapped through the approval

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#874]
### How to reproduce?
1. I changed the demo to have a button for directly calling one of the exposed RPC like `GET_CONNECTED_IDENTITY_DATA` through calling `client.getConnectedIdentity()`
2. I did step (1) without going trough `client.connect()` which has the approval step. 
3. I did get output showing the connected identity metadata.

### How to resolve?
I think all the exposed APIs should be handling the Approval part internally inside the background script. Which means that all the RPC calls inside the Provider are protected from inside the extension. 

- Screenshot of the button `Get Connected Identity`
![Image](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/72e2c500-72f9-4c22-8bbf-50dfded0e76d)

- Screenshot of the output data after clicking on `Get Connected Identity`
![Image](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/da7033c4-0ee4-49db-9d33-255b4c36d64f)

```[tasklist]
### Tasks
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/897
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/898
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/899
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/900
- [ ] https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/932
```
